fix limitation for size of data:*:base64 images and max length of the html input line
michaelrsweet/htmldoc pull request #454
Opened 2021-11-13 16:53 UTC by Shaeto

1. currently maximum size of <img ... src='data:...:base64.....' ..> image is ~7k
2. maximum length of input line for input html document is 10240 (limited by code in htmllib.cxx)

this patch removes these limitations

test command is:

cat ./test.html | htmldoc --webpage -t pdf - > test.pdf

test.html is attached

[test.html.zip](https://github.com/michaelrsweet/htmldoc/files/7532422/test.html.zip)

2021-11-13 19:59 UTC, michaelrsweet requested changes
I'm OK wth allowing larger strings, but I don't want them to be unbounded - HTMLDOC is used to provide live conversions on web servers.

2021-11-13 19:59 UTC, michaelrsweet commented on htmldoc/file.c
> +      len = strlen(filename);
I'd prefer to have some limits in place to avoid out-of-control memory allocations.

2021-11-13 19:59 UTC, michaelrsweet commented on htmldoc/htmllib.cxx
> +#include <string>
... and while I do use C++ in HTMLDOC, I've avoided pulling in the standard C++ library since it seems to change with every major OS release on multiple platforms...

2021-11-13 20:34 UTC, Shaeto commented on htmldoc/htmllib.cxx
> +#include <string>
i thought this file was renamed to .cxx keeping in mind idea write c++ code :)

imho std::string is very very stable, it can be replaced by std::vector or do you suggest to implement custom byte vector ?

2021-11-13 20:37 UTC, Shaeto commented on htmldoc/file.c
> +      len = strlen(filename);
agree... actually it must be limited in htmllib.cxx line(s) reader

10240 is definitely too small, limit it to something x100 times bigger ? is not big problem for server application ?

2021-11-13 21:26 UTC, michaelrsweet commented on htmldoc/htmllib.cxx
> +#include <string>
libstdc++ has changed in incompatible ways 6 times in the last ~20 years, making it very hard to provide *binaries* of HTMLDOC that depend on it.

2021-11-13 21:30 UTC, michaelrsweet commented on htmldoc/file.c
> +      len = strlen(filename);
That might work, will run the numbers...

2024-11-21 20:14 UTC, michaelrsweet commented
Will consider increasing limits in a future release, but will not be incorporating libstdc++ usage or these specific changes, sorry.

2024-11-21 20:14 UTC, closed without merging